### PR TITLE
Project Back End Skeleton

### PR DESCRIPTION
**Pull request by Apexal**
This sets up a NodeJS server KoaJS including routes.

**Back End Team** please review **and accept** this code to get a taste of KoaJS, if you have any questions at all please please please please comment here and ask them. Tiny questions or large questions. There are no bad questions.

### CODE REVIEW

**Comment by AbigailMedina** [comment]
"no-multiple-empty-lines": [1, {"max": 1, "maxEOF": 1}],
    "no-trailing-spaces": [1, { "skipBlankLines": true }],
    "no-mixed-spaces-and-tabs": [1],
    "no-unused-vars": [1, { "allow": ["warn", "error"] } ],
    "no-console": [1, { "allow": ["warn", "error"] } ]
wanna add some more rules? theyre good to keep the style consistent between people

**Comment by kvverti** [comment]
I recommend adding `package-lock.json` to the `.gitignore` so we don't have bogus diffs.

**Comment by kvverti** [comment]
@Apexal Should we install `node` to run the scripts?

**Comment by Apexal** [comment]
@AbigailMedina Definitely, I will add those rules and look into further ones.

**Comment by Apexal** [comment]
> I recommend adding `package-lock.json` to the `.gitignore` so we don't have bogus diffs.
@kvverti 

I had read up on best practices with this [especially here](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5) but after your comment and rereading it does seem best to ignore it. I'll get on that

**Comment by kvverti** [comment]
@Apexal Is there a reason we are creating a new Router in `server/routes/home.js` only to throw it away and assign its routes to the one in `server/index.js`?

**Comment by Apexal** [comment]
> @Apexal Is there a reason we are creating a new Router in `server/routes/home.js` only to throw it away and assign its routes to the one in `server/index.js`?
@kvverti 	

The route system is overly-complicated at the moment because of the lack of routes at the moment.

But the way its set up now splits up the routes and their controllers. Each category of routes, e.g. `/assignments`, `/users`, etc. are considered root routes so they'll get their own file in `/server/routes/`. `/server/routes/index.js` is the main router that sets up the different category routes. It is the file that runs when `require('/server/routes')` is run from `/server/index.js`, because it is named `index`.

It will come together when we start adding routes.

**Pull request merged**
