### PR TITLE
Changed course sorting

### PR DESCRIPTION
**Pull request by robere2**
changed sorting from `originalTitle` to `title` at `/api/courses` endpoint

Fixes issue #409

### CODE REVIEW

**Comment by robere2** [comment]
I think I did this right but please make sure.

**Comment by Apexal** [comment]
This looks good, but I'm curious as to what you think is best to sort by. Should we sort alphabetically or should we take info about the course into account, e.g. sort by course level (4000 - 1000) or similar?

**Comment by aidan-lane** [comment]
Maybe a middle ground would be to sort by _first_ letter alphabetically, and then sort each 'letter section' using the course code numbers. It'd be interesting to see how this looks, but it might be less readable and intuitive.

**Comment by Apexal** [comment]
I think the ideal would be that but swapped: first sort by level and then alphabetically. 
This is tricky though since it can't be done on the database side with `.sort()` since the course level is in a field with the subject (e.g. `BIOL 1010` instead of `1010`).

Sorting can be done after they are queried with a custom function like
```js
function sortCourse(c1, c2) {
	const c1Level = parseInt(c1.summary.split(' ')[1]);
	const c2Level = parseInt(c2.summary.split(' ')[1]);
	
	if (c1Level < c2Level) {
		return 1;
	} else if (c1Level > c2Level) {
		return -1;
	}
	
	if (c1.title > c2.title) {
		return 1;
	} else if (c1.title < c2.title) {
		return -1;
	}

	return 0;
}
```

The 1,0,-1's might be off, I quick typed this off the top of my head

**Comment by robere2** [comment]
I thought about this and how sorting could be improved, however I think this almost complicates things more rather than less. At the moment, no more than 5-7 courses should be expected to appear on the course list (including Other). Considering how many different schools there are, by having sorting more complex than alphabetical, it might not be immediately obvious how things are sorted without at least 10 or 15 items. With such few items, more complex sorting isn't really necessary, however I'm also not sure it's that big of a deal if it's added.

Also, note that there's not many places where the school or the course level are shown in a list (from what I've seen), which might make it less obvious.

If we were to sort based off of school and then alphabetical:

 vs sorting purely alphabetical:


I prefer the latter, but again, with so few items I don't think it matters that much and I'd be fine either way.

**Comment by Apexal** [comment]
Perhaps a better metric is the number of credits the course is being taken for?

**Comment by robere2** [comment]
I think this is the optimal solution for now.

**Review by Apexal — APPROVED** [review]
Looks great!

**Pull request merged**
